name: Quay UI Integration Tests

on:
  pull_request:
    branches:
    - "*"

jobs:
  # TODO: Focusing on e2e tests for now, will implement this later
  # cypress-component:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4.2.0
  #       with:
  #         browser: chrome
  #         build: npm run build
  #         start: npm run start:integration
  #         wait-on: 'http://localhost:9000'
  #         wait-on-timeout: 120
  #       env:
  #         MOCK_API: true
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Quay Repository
        uses: actions/checkout@v3
        with:
          repository: bcaton85/quay
          path: './quay'
          ref: ui-ci
      - name: Start Quay
        run: |
          # TODO: figure out how to cache build deps
          # docker buildx create --use --driver=docker-container
          # docker buildx build -t localhost/quay-local:latest --cache-to type=gha --cache-from type=gha .
          cd quay && make ci-up
      - name: Load Test Data
        run: |
          sleep 15s
          docker cp ./cypress/test/quay-test-data.txt quay-db:/tmp/data.txt
          docker exec -t quay-db bash -c 'psql quay -U quay < /tmp/data.txt'
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          build: npm run build
          start: npm run start:integration
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 120
        env:
          REACT_QUAY_APP_API_URL: http://localhost:8080
      # Used for debugging. Uncomment to upload screenshots  
      # and videos of running tests to diagnose issues.
      # - uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
